ubuntu@ip-172-31-4-18:~/FinFlow$ ls
README.md  client  docker-compose.yml  package-lock.json  server
ubuntu@ip-172-31-4-18:~/FinFlow$ vim docker-compose.yml












































  server:
    build:
      context: ./server
      dockerfile: Dockerfile

    image: finflow-server:1.0
    container_name: finflow-server

    restart: unless-stopped

    env_file:
      - ./server/.env

    ports:
      - "5000:5000"

    depends_on:
      - mongo

    networks:
      - finflow-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile

    image: finflow-client:1.0
    container_name: finflow-client

    restart: unless-stopped

    ports:
      - "3000:80"

    depends_on:
      - server

    networks:
      - finflow-network

volumes:
  mongo_data:

"docker-compose.yml" 64L, 884B                                                                                                  34,15         84%
