apiVersion: v1
kind: ConfigMap
metadata:
  name: finflow-config
  namespace: finflow

data:
  NODE_ENV: "production"
  PORT: "5000"
  MONGODB_URI: "mongodb://admin:StrongPassword123@mongodb-service:27017/finflow?authSource=admin"
