apiVersion: v1
kind: Secret
metadata:
  name: finflow-secret
  namespace: finflow
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: admin
  MONGO_INITDB_ROOT_PASSWORD: StrongPassword123
  JWT_SECRET: your-super-secret-jwt-key
